# Generated by Django 3.2.9 on 2022-07-21 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('purchased_price', models.IntegerField(blank=True, null=True)),
                ('actual_price', models.IntegerField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('salary', 'Salary'), ('pay', 'Pay'), ('received', 'Received'), ('spend', 'Spend')], default='spend', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
